version: '3'
services:
  nging:
    container_name: test-ubuntu-firewall
    image: test-ubuntu-firewall
    depends_on:
      - mysql
    expose:
      - 28181
    ports:
      - 28181:28181
    links:
      - "mysql:mysql"
    volumes:
      - /Users/hank/go/src/:/root/go/src/
      - /Users/hank/go/src/:/Users/hank/go/src/
    working_dir: /root/go/src/github.com/nging-plugins/firewallmanager/example
    privileged: true
    restart: always
  mysql:
    container_name: nging-mysql
    image: mysql
    volumes:
      - ./docker-data/mysql/data:/var/lib/mysql/
      - ./docker-data/mysql/conf:/etc/mysql/conf.d/
      - ./docker-data/mysql/run:/var/run/mysqld/
    expose:
      - 3306
    cap_add:
      - SYS_NICE 
    environment:
      - MYSQL_ROOT_PASSWORD=root
    command: --default-authentication-plugin=mysql_native_password
    restart: always